import type { MetadataRoute } from "next";

const baseUrl = "https://ssctoolshub.com";

export default function sitemap(): MetadataRoute.Sitemap {
  const routes = [
    "",
    "/about",
    "/blog",
    "/contact",
    "/disclaimer",
    "/privacy-policy",
    "/resources",
    "/pyqs",
    "/syllabus",
    "/terms-and-conditions",
    "/tools",

    "/ssc-cgl",
    "/ssc-cgl-notification",
    "/ssc-cgl-syllabus",
    "/ssc-cgl-exam-pattern",
    "/ssc-cgl-exam-date",
    "/ssc-cgl-admit-card",
    "/ssc-cgl-books",
    "/ssc-cgl-cutoff",
    "/ssc-cgl-salary",
    "/ssc-cgl-job-profile",
    "/ssc-cgl-post-preference",

    "/ssc-chsl",
    "/ssc-chsl-notification",
    "/ssc-chsl-syllabus",
    "/ssc-chsl-exam-pattern",
    "/ssc-chsl-admit-card",
    "/ssc-chsl-books",
    "/ssc-chsl-cutoff",
    "/ssc-chsl-salary",

    "/ssc-mts",
    "/ssc-mts-notification",
    "/ssc-mts-syllabus",
    "/ssc-mts-exam-pattern",
    "/ssc-mts-admit-card",
    "/ssc-mts-books",
    "/ssc-mts-cutoff",
    "/ssc-mts-salary",

    "/ssc-gd",
    "/ssc-gd-notification",
    "/ssc-gd-syllabus",
    "/ssc-gd-exam-pattern",
    "/ssc-gd-admit-card",
    "/ssc-gd-books",
    "/ssc-gd-cutoff",
    "/ssc-gd-salary",

    "/ssc-stenographer",
    "/ssc-stenographer-notification",
    "/ssc-stenographer-syllabus",
    "/ssc-stenographer-exam-pattern",
    "/ssc-stenographer-admit-card",
    "/ssc-stenographer-cutoff",
    "/ssc-stenographer-salary",

    "/tools/age-calculator",
    "/tools/current-affairs-feed",
    "/tools/current-affairs-quiz",
    "/tools/eligibility-checker",
    "/tools/exam-countdown",
    "/tools/gk-flashcards",
    "/tools/goal-planner",
    "/tools/marks-calculator",
    "/tools/mock-analyzer",
    "/tools/motivation-generator",
    "/tools/notes-manager",
    "/tools/pdf-mock-converter",
    "/tools/percentage-calculator",
    "/tools/performance-tracker",
    "/tools/pomodoro-timer",
    "/tools/quiz-challenge",
    "/tools/rank-predictor",
    "/tools/revision-planner",
    "/tools/study-planner",
    "/tools/study-tracker",
    "/tools/syllabus-viewer",
    "/tools/timetable-generator",
    "/tools/topic-progress-tracker",
    "/tools/weakness-analyzer",
  ];

  return routes.map((route) => ({
    url: `${baseUrl}${route}`,
    lastModified: new Date(),
    changeFrequency: route === "" ? "daily" : "weekly",
    priority: route === "" ? 1 : 0.8,
  }));
}